MODEL = "gpt-4.1-nano"
TYPEWRITER_INTERVAL_MS: int = 20
THINK_INTERVAL_MS: int = 100
MIN_THINK_TIME_MS: int = 1000
BLOCK_DELAY_S: int = 15
MESSAGE_THRESHOLD: int = 5
APP_TITLE = "ChatGPT"
SONA_ID: str = ""